### ISSUE TITLE
Hey how do you make the .env file

### ISSUE THREAD

**Issue by godgutten** [LiuAndre/discord-sticky-message-bot#3]
Hey, what do I need to name the .env file? Is it possible to make a guide that goes more into detail?

**Comment by godgutten** [comment]
So the bot is now running

https://i.imgur.com/b4ZYUyj.png


And I now ran the -stick command and it sent my command but it's not resending the message for some reason.

https://i.imgur.com/zPaRaM4.png

**Comment by LiuAndre** [comment]
> Hey, what do I need to name the .env file? Is it possible to make a guide that goes more into detail?
Now I include `.env.example` and update `README.md` to make `.env` file creation more easy


> So the bot is now running
> https://i.imgur.com/b4ZYUyj.png
> And I now ran the -stick command and it sent my command but it's not resending the message for some reason.
> https://i.imgur.com/zPaRaM4.png
My bad, I make last minute change before commit the code to this repository and does not check if the code is work or not.
`MAX_MESSAGE_COUNT` from `.env` is `string` but I use strict comparison and compare it to a `number`.
Now I just fix it and test it, it should work like a charm now. 😄
